import {normalizeScientificName} from './catalogExpansion';
export interface ClinicalPattern {names:string[];title:string;manifestations:string[];context:string;sourceUrl:string}
export const CLINICAL_PATTERNS:ClinicalPattern[]=[
 {names:['Toxoplasma gondii'],title:'Tríada clásica de toxoplasmosis congénita',manifestations:['Retinocoroiditis','Hidrocefalia','Calcificaciones intracraneales'],context:'Corresponde a infección congénita; no resume todas las formas de toxoplasmosis. La tríada puede estar incompleta y no sustituye la confirmación etiológica.',sourceUrl:'https://ndc.services.cdc.gov/case-definitions/congenital-toxoplasmosis-2024/'},
 {names:['Rubella virus','Virus de la rubéola','Rubivirus rubellae'],title:'Tríada del síndrome de rubéola congénita',manifestations:['Alteración auditiva','Cardiopatía congénita','Anomalías oculares, como cataratas'],context:'Manifestaciones del síndrome congénito, distintas del exantema de la infección adquirida. No todos los casos presentan las tres.',sourceUrl:'https://archive.cdc.gov/www_cdc_gov/ncbddd/birthdefects/surveillancemanual/chapters/chapter-5/chapter5-1.html'},
 {names:['Trypanosoma cruzi'],title:'Signo de Romaña',manifestations:['Edema unilateral de ambos párpados'],context:'Puede aparecer tras inoculación conjuntival en Chagas agudo. Su ausencia no excluye infección; una fotografía de edema palpebral aislado no confirma la causa.',sourceUrl:'https://www.cdc.gov/parasites/cme/chagas/glossary.html'},
 {names:['Measles virus','Virus del sarampión','Morbillivirus hominis'],title:'Manchas de Koplik',manifestations:['Enantema con pequeños puntos blancos o blanco azulados sobre mucosa bucal eritematosa'],context:'El CDC las describe como patognomónicas del sarampión. La identificación clínica requiere evaluación y confirmación según el contexto epidemiológico.',sourceUrl:'https://www.cdc.gov/measles/hcp/clinical-overview/index.html'},
 {names:['Corynebacterium diphtheriae'],title:'Pseudomembrana de la difteria respiratoria',manifestations:['Membrana gris blanquecina adherente en amígdalas, faringe o laringe'],context:'Hallazgo característico, pero otras enfermedades pueden producir membranas. La identificación de la bacteria y su toxigenicidad requiere laboratorio.',sourceUrl:'https://www.cdc.gov/surv-manual/php/table-of-contents/chapter-1-diphtheria.html'},
 {names:['Candida albicans','Candida spp.'],title:'Candidiasis orofaríngea · muguet',manifestations:['Placas blancas','Enrojecimiento o dolor en boca y garganta'],context:'La manifestación corresponde a candidiasis; por sí sola no identifica la especie de Candida. No toda placa blanca es candidiasis.',sourceUrl:'https://www.cdc.gov/candidiasis/about/index.html'},
 {names:['Clostridium tetani'],title:'Tétanos · trismo y espasmos',manifestations:['Trismo: dificultad para abrir la mandíbula','Rigidez muscular','Espasmos generalizados que pueden desencadenarse por estímulos'],context:'El diagnóstico es clínico. No existe una prueba de laboratorio que por sí sola confirme o descarte tétanos. Es una urgencia médica; no se presenta como una tríada diagnóstica.',sourceUrl:'https://www.cdc.gov/tetanus/hcp/clinical-signs/index.html'},
 {names:['Bordetella pertussis'],title:'Tos ferina · paroxismos de tos',manifestations:['Accesos repetidos de tos','Gallo inspiratorio','Vómito después de toser'],context:'El gallo puede faltar, especialmente en lactantes; la presentación varía con la edad y la vacunación. Estos hallazgos no constituyen una tríada confirmatoria.',sourceUrl:'https://www.cdc.gov/pertussis/signs-symptoms/index.html'},
 {names:['Borrelia burgdorferi'],title:'Enfermedad de Lyme · eritema migratorio',manifestations:['Lesión eritematosa que se expande gradualmente'],context:'Puede tener aclaramiento central, pero no siempre adopta forma de diana. El contexto de exposición y viaje es esencial; la lesión no demuestra circulación en Guatemala y existen imitadores.',sourceUrl:'https://www.cdc.gov/lyme/signs-symptoms/index.html'},
 {names:['Parvovirus B19','Human parvovirus B19'],title:'Eritema infeccioso · mejilla abofeteada',manifestations:['Eritema facial característico en niños','Exantema corporal que puede adquirir aspecto reticulado'],context:'En adultos puede predominar dolor articular sin el exantema típico. La apariencia no sustituye evaluación; embarazo, inmunosupresión y trastornos hemolíticos requieren especial atención.',sourceUrl:'https://www.cdc.gov/parvovirus-b19/about/index.html'},
 {names:['Varicella-zoster virus','Virus de la varicela','VVZ','VZV'],title:'Varicela · lesiones en diferentes estadios',manifestations:['Máculas, pápulas, vesículas y costras que pueden coexistir','Exantema pruriginoso'],context:'Describe la presentación habitual en personas no vacunadas. Tras vacunación puede ser más leve y sin vesículas típicas; se necesita confirmación de laboratorio según el caso.',sourceUrl:'https://www.cdc.gov/chickenpox/hcp/clinical-signs/index.html'},
 {names:['Treponema pallidum'],title:'Sífilis · chancro y exantema secundario',manifestations:['Chancro de sífilis primaria, habitualmente firme, redondo e indoloro','Exantema en sífilis secundaria, que puede afectar palmas y plantas'],context:'Son etapas diferentes. La lesión primaria puede ser extragenital y variar; la fotografía no establece el estadio de otra persona ni sustituye las pruebas de sífilis.',sourceUrl:'https://www.cdc.gov/syphilis/about/index.html'},
 {names:['Trichophyton rubrum','Trichophyton mentagrophytes'],title:'Dermatofitosis · tiñas por localización',manifestations:['Tiña corporal: lesiones cutáneas, a menudo anulares','Tiña del pie: descamación o lesiones plantares e interdigitales'],context:'Tinea corporis y tinea pedis nombran la localización. El aspecto no determina la especie; las fotografías se atribuyen únicamente a la especie documentada por el registro original.',sourceUrl:'https://www.cdc.gov/ringworm/about/index.html'},
];
export function clinicalPatterns(name:string){return CLINICAL_PATTERNS.filter(p=>p.names.some(n=>normalizeScientificName(n)===normalizeScientificName(name)));}
