import {normalizeScientificName} from './catalogExpansion';
export interface ClinicalPattern {names:string[];title:string;manifestations:string[];context:string;sourceUrl:string}
export const CLINICAL_PATTERNS:ClinicalPattern[]=[
 {names:['Toxoplasma gondii'],title:'Tríada clásica de toxoplasmosis congénita',manifestations:['Retinocoroiditis','Hidrocefalia','Calcificaciones intracraneales'],context:'Corresponde a infección congénita; no resume todas las formas de toxoplasmosis. La tríada puede estar incompleta y no sustituye la confirmación etiológica.',sourceUrl:'https://ndc.services.cdc.gov/case-definitions/congenital-toxoplasmosis-2024/'},
 {names:['Rubella virus','Virus de la rubéola','Rubivirus rubellae'],title:'Tríada del síndrome de rubéola congénita',manifestations:['Alteración auditiva','Cardiopatía congénita','Anomalías oculares, como cataratas'],context:'Manifestaciones del síndrome congénito, distintas del exantema de la infección adquirida. No todos los casos presentan las tres.',sourceUrl:'https://archive.cdc.gov/www_cdc_gov/ncbddd/birthdefects/surveillancemanual/chapters/chapter-5/chapter5-1.html'},
 {names:['Trypanosoma cruzi'],title:'Signo de Romaña',manifestations:['Edema unilateral de ambos párpados'],context:'Puede aparecer tras inoculación conjuntival en Chagas agudo. Su ausencia no excluye infección; una fotografía de edema palpebral aislado no confirma la causa.',sourceUrl:'https://www.cdc.gov/parasites/cme/chagas/glossary.html'},
 {names:['Measles virus','Virus del sarampión','Morbillivirus hominis'],title:'Manchas de Koplik',manifestations:['Enantema con pequeños puntos blancos o blanco azulados sobre mucosa bucal eritematosa'],context:'El CDC las describe como patognomónicas del sarampión. La identificación clínica requiere evaluación y confirmación según el contexto epidemiológico.',sourceUrl:'https://www.cdc.gov/measles/hcp/clinical-overview/index.html'},
 {names:['Corynebacterium diphtheriae'],title:'Pseudomembrana de la difteria respiratoria',manifestations:['Membrana gris blanquecina adherente en amígdalas, faringe o laringe'],context:'Hallazgo característico, pero otras enfermedades pueden producir membranas. La identificación de la bacteria y su toxigenicidad requiere laboratorio.',sourceUrl:'https://www.cdc.gov/surv-manual/php/table-of-contents/chapter-1-diphtheria.html'},
 {names:['Candida albicans','Candida spp.'],title:'Candidiasis orofaríngea · muguet',manifestations:['Placas blancas','Enrojecimiento o dolor en boca y garganta'],context:'La manifestación corresponde a candidiasis; por sí sola no identifica la especie de Candida. No toda placa blanca es candidiasis.',sourceUrl:'https://www.cdc.gov/candidiasis/about/index.html'},
];
export function clinicalPatterns(name:string){return CLINICAL_PATTERNS.filter(p=>p.names.some(n=>normalizeScientificName(n)===normalizeScientificName(name)));}
