import {useMemo,useState} from 'react';
import {BookOpen,Microscope,Activity,Pill,ShieldCheck,Layers,MapPin,Library,ChevronDown,Search,ArrowRight} from 'lucide-react';
import type {Microorganism} from '../types/microorganism';
import type {DocumentPageLink} from '../services/documentAtlas';
import {DOCUMENT_SECTION_LABELS} from '../services/documentAtlas';
import {FICHA_SECTIONS,organizeFichaDocuments,type FichaSectionId,type FichaExcerpt} from '../services/academicFicha';
import {learningSupplement,curatedImages} from '../services/learningAtlas';
import {safeHttpsUrl} from './SourceImageGallery';
import {ParasiteStageVisualizer} from './ParasiteStageVisualizer';
import {RegionalReferences} from './RegionalReferences';

const icons={identity:Microscope,clinical:Activity,diagnosis:Search,treatment:Pill,prevention:ShieldCheck,cycle:Layers,guatemala:MapPin,sources:Library};
function Facts({title,items}:{title:string;items:(string|undefined)[]}){
  const available=items.filter((s):s is string=>!!s?.trim());
  if(!available.length)return null;
  return <section className="rounded-xl border border-slate-200 bg-white p-4 sm:p-5"><h4 className="mb-3 text-xs font-bold uppercase tracking-wider text-slate-500">{title}</h4><ul className="space-y-2.5 text-sm leading-7 text-slate-700">{available.map((s,i)=><li key={i} className="flex gap-2.5"><span className="mt-3 h-1 w-1 shrink-0 rounded-full bg-sky-600"/><span className="whitespace-pre-wrap break-words">{s}</span></li>)}</ul></section>;
}
function Excerpts({entries}:{entries:FichaExcerpt[]}){
  const [limit,setLimit]=useState(6);
  if(!entries.length)return null;
  return <section className="space-y-3"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-sky-800"><BookOpen size={15}/>Contenido de tus documentos · {entries.length} fragmentos</div>
    {entries.slice(0,limit).map((entry,i)=><article key={i} className="overflow-hidden rounded-xl border border-sky-100 bg-white shadow-xs"><div className="border-l-4 border-sky-600 px-4 py-4 sm:px-5"><h4 className="mb-2 text-xs font-semibold text-sky-800">{DOCUMENT_SECTION_LABELS[entry.section]}</h4><p className="whitespace-pre-wrap break-words text-sm leading-7 text-slate-800">{entry.text.length>1200?entry.text.slice(0,1200)+'…':entry.text}</p>{entry.text.length>1200&&<details className="mt-3 text-sm"><summary className="cursor-pointer font-semibold text-sky-800">Leer fragmento completo</summary><p className="mt-3 whitespace-pre-wrap break-words leading-7">{entry.text}</p></details>}</div>
      <footer className="space-y-2 border-t border-sky-100 bg-sky-50/60 px-4 py-3 text-xs leading-5 text-slate-600">{entry.sources.map(({page},j)=><div key={j}><p className="font-semibold text-slate-800">{page.document.title} · página {page.pageNumber}</p><p>{page.document.authorOrInstitution} · {page.document.sourceTier}</p>{page.association==='heading'&&<p>Continuación del epígrafe de página {page.headingPage}; comprobar atribución.</p>}{page.mentionedNames.length>1&&<p className="text-amber-900">Página compartida con: {page.mentionedNames.join(', ')}. Lee el contexto antes de atribuir el contenido a esta especie.</p>}</div>)}</footer>
    </article>)}
    {entries.length>limit&&<button onClick={()=>setLimit(n=>n+6)} className="rounded-lg border border-sky-200 bg-white px-4 py-2 text-sm font-semibold text-sky-800">Leer otros fragmentos ({entries.length-limit} restantes)</button>}
  </section>;
}
export function AcademicFicha({organism:o,pages,overview,onOpen}:{organism:Microorganism;pages:DocumentPageLink[];overview:boolean;onOpen:(mode:'imagenes'|'ciclo'|'documentos'|'completa')=>void}){
  const [selected,setSelected]=useState<FichaSectionId|'all'>('all');
  const [query,setQuery]=useState('');
  const grouped=useMemo(()=>organizeFichaDocuments(pages),[pages]);
  const supplement=learningSupplement(o),images=curatedImages(o);
  const m=o.microbiologyCharacteristics;
  const documentCount=new Set(pages.map(p=>p.document.id)).size;
  const q=query.toLocaleLowerCase('es').trim();
  const excerpts=(id:FichaSectionId)=>grouped[id].filter(e=>!q||e.text.toLocaleLowerCase('es').includes(q)||e.sources.some(s=>s.page.document.title.toLocaleLowerCase('es').includes(q)));
  const visible=FICHA_SECTIONS.filter(s=>(selected==='all'||selected===s.id)&&(!q||excerpts(s.id).length));
  return <div className="space-y-6">
    <section className="relative overflow-hidden rounded-2xl bg-slate-900 p-5 text-white sm:p-7"><div className="absolute right-0 top-0 h-36 w-36 rounded-full bg-sky-500/10" aria-hidden="true"/><p className="text-[10px] font-bold uppercase tracking-[.22em] text-sky-300">Dossier académico · InfectoAtlas GT</p><h3 className="mt-2 text-xl font-semibold sm:text-2xl">{overview?'Guía de estudio del microorganismo':'Ficha académica completa'}</h3><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300">{o.documentIndexed?'La información de tu biblioteca se presenta en apartados de estudio, conservando el texto y sus páginas de origen.':'Consulta los datos guardados y amplía cada tema con los documentos vinculados a esta ficha.'}</p>
      <dl className="mt-5 grid grid-cols-3 gap-3 border-t border-white/10 pt-4"><div><dt className="text-xs text-slate-400">Documentos</dt><dd className="mt-1 text-xl font-semibold">{documentCount}</dd></div><div><dt className="text-xs text-slate-400">Páginas vinculadas</dt><dd className="mt-1 text-xl font-semibold">{pages.length}</dd></div><div><dt className="text-xs text-slate-400">Imágenes con fuente</dt><dd className="mt-1 text-xl font-semibold">{images.length}</dd></div></dl>
    </section>
    {overview&&<div className="grid gap-3 sm:grid-cols-2"><Facts title="Identificación" items={[!o.documentIndexed?o.morphology.shape:undefined,o.morphology.gramStain,o.taxonomy.family!=='Taxonomía completa pendiente'?o.taxonomy.family:undefined]}/><Facts title="Claves diagnósticas" items={[...o.diagnosticMethods.map(d=>`${d.method}: ${d.keyFindings}`),...(supplement?.diagnosticPearls??[])]}/></div>}
    <div className="grid gap-3 sm:grid-cols-3"><button onClick={()=>onOpen('imagenes')} className="flex items-center justify-between rounded-xl border border-slate-200 bg-white p-4 text-left text-sm font-semibold text-slate-800">Atlas de imágenes <ArrowRight size={16}/></button>{!!supplement?.cycles.length&&<button onClick={()=>onOpen('ciclo')} className="flex items-center justify-between rounded-xl border border-emerald-200 bg-emerald-50/50 p-4 text-left text-sm font-semibold text-emerald-900">Ciclo CDC y estadios <ArrowRight size={16}/></button>}<button onClick={()=>onOpen('documentos')} className="flex items-center justify-between rounded-xl border border-slate-200 bg-white p-4 text-left text-sm font-semibold text-slate-800">Leer páginas originales <ArrowRight size={16}/></button></div>
    <div className="grid items-start gap-5 lg:grid-cols-[220px_minmax(0,1fr)]">
      <nav aria-label="Índice de la ficha" className="rounded-xl border border-slate-200 bg-white p-3 lg:sticky lg:top-0"><p className="px-2 pb-2 text-[10px] font-bold uppercase tracking-widest text-slate-500">Índice académico</p><button onClick={()=>{setSelected('all');setQuery('');}} aria-current={selected==='all'?'true':undefined} className={`mb-1 w-full rounded-lg px-3 py-2.5 text-left text-sm font-semibold ${selected==='all'?'bg-slate-900 text-white':'text-slate-600 hover:bg-slate-50'}`}>Ver toda la ficha</button><label className="block lg:hidden text-xs text-slate-500">Seleccionar apartado<select aria-label="Seleccionar apartado" value={selected} onChange={e=>{setSelected(e.target.value as FichaSectionId|'all');setQuery('');}} className="mt-2 w-full rounded-lg border border-slate-200 bg-white p-3 text-sm text-slate-800"><option value="all">Toda la ficha</option>{FICHA_SECTIONS.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label><div className="hidden gap-1 lg:grid lg:grid-cols-1">{FICHA_SECTIONS.map((s,i)=>{const Icon=icons[s.id];return <button key={s.id} onClick={()=>{setSelected(s.id);setQuery('');}} aria-current={selected===s.id?'true':undefined} className={`flex items-start gap-2 rounded-lg px-2 py-2.5 text-left text-xs leading-5 transition-colors ${selected===s.id?'bg-sky-100 font-semibold text-sky-900':'text-slate-600 hover:bg-slate-50'}`}><Icon size={15} className="mt-0.5 shrink-0"/><span><span className="mr-1 text-[10px] opacity-60">{String(i+1).padStart(2,'0')}</span>{s.title}</span></button>;})}</div></nav>
      <div className="min-w-0 space-y-5"><label className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white px-4 py-3"><Search size={17} className="shrink-0 text-slate-400"/><span className="sr-only">Buscar en los documentos de la ficha</span><input className="min-w-0 flex-1 bg-transparent text-sm outline-none" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar en tus documentos: PCR, muestra, ciclo…"/></label>{q&&<p className="text-xs text-slate-500">Resultados del texto documental. Borra la búsqueda para ver también los datos guardados.</p>}
        {!visible.length&&<p className="rounded-xl border border-dashed p-5 text-sm text-slate-600">No hay fragmentos para esta búsqueda.</p>}
        {visible.map(s=>{const Icon=icons[s.id];const entries=excerpts(s.id);return <section key={s.id} aria-labelledby={`academic-${s.id}`} className="space-y-4 rounded-2xl border border-slate-200 bg-slate-50/70 p-4 sm:p-6"><header className="flex items-start gap-3 border-b border-slate-200 pb-4"><div className="rounded-xl bg-white p-2.5 text-sky-800 shadow-xs"><Icon size={20}/></div><div><h3 id={`academic-${s.id}`} className="text-lg font-bold text-slate-900">{s.title}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{s.subtitle}</p></div></header>
          {!q&&<>
            {s.id==='identity'&&<><dl className="grid grid-cols-2 gap-3 rounded-xl border border-slate-200 bg-white p-4 sm:grid-cols-3">{Object.entries(o.taxonomy).filter(([,v])=>!!v).map(([k,v])=><div key={k}><dt className="text-[10px] font-bold uppercase tracking-wider text-slate-500">{({domain:'Dominio',kingdom:'Reino',phylum:'Filo',classTaxon:'Clase',orderTaxon:'Orden',family:'Familia',genus:'Género',species:'Especie / grupo'} as Record<string,string>)[k]}</dt><dd className="mt-1 break-words text-sm text-slate-800">{v}</dd></div>)}</dl>{!o.documentIndexed&&<Facts title="Morfología" items={[o.morphology.shape,`Tamaño: ${o.morphology.size}`,o.morphology.arrangement,o.morphology.gramStain,...o.morphology.specialStructures]}/>}<div className="grid gap-3 sm:grid-cols-2"><Facts title="Crecimiento y metabolismo" items={[m.metabolism,m.optimalTemp&&`Temperatura: ${m.optimalTemp}`,m.growthTime&&`Tiempo: ${m.growthTime}`]}/><Facts title="Medios y pruebas bioquímicas" items={[...(m.cultureMedia??[]),...(m.keyBiochemicalTests??[])]}/></div><Facts title="Estructuras externas e internas" items={o.externalAndInternalStructures}/></>}
            {s.id==='clinical'&&<><Facts title="Factores de virulencia" items={o.virulenceFactors.map(v=>`${v.name}: ${v.mechanism}`)}/>{o.associatedDiseases.map((d,i)=><section key={i} className="rounded-xl border border-slate-200 bg-white p-4"><h4 className="font-semibold text-slate-900">{d.name}</h4><p className="mt-2 text-sm leading-7">{d.description}</p>{d.typicalIncubation&&<p className="mt-2 text-xs text-slate-500">Incubación: {d.typicalIncubation}</p>}<Facts title="Presentación clínica" items={d.clinicalPresentation}/></section>)}<div className="grid gap-3 sm:grid-cols-2"><Facts title="Signos y síntomas" items={o.signsAndSymptoms}/><Facts title="Complicaciones" items={o.complications}/></div></>}
            {s.id==='diagnosis'&&<><Facts title="Muestras clínicas" items={o.clinicalSpecimens}/>{o.diagnosticMethods.map((d,i)=><section key={i} className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h4 className="font-semibold text-slate-900">{d.method}</h4><span className="rounded bg-slate-100 px-2 py-1 text-xs text-slate-600">Rol registrado: {d.standardRole}</span></div><p className="mt-3 text-sm leading-7">{d.keyFindings}</p>{d.turnaroundTime&&<p className="mt-2 text-xs text-slate-500">Tiempo de respuesta: {d.turnaroundTime}</p>}</section>)}<Facts title="Hallazgos de laboratorio" items={o.labFindings}/><Facts title="Claves de interpretación · atlas documentado" items={supplement?.diagnosticPearls??[]}/></>}
            {s.id==='treatment'&&<><p className="rounded-xl border border-amber-100 bg-amber-50 p-4 text-xs leading-6 text-amber-900">{o.treatment.disclaimer}</p><div className="grid gap-3 sm:grid-cols-2"><Facts title="Primera línea registrada" items={o.treatment.firstLine}/><Facts title="Alternativas registradas" items={o.treatment.alternatives}/></div><Facts title="Contraindicaciones y alertas" items={o.treatment.contraindicationsOrAlerts??[]}/>{o.treatment.resistanceNotes&&<Facts title="Notas de resistencia" items={[o.treatment.resistanceNotes]}/>}</>}
            {s.id==='prevention'&&<><div className="grid gap-3 sm:grid-cols-2"><Facts title="Reservorios" items={o.reservoir}/><Facts title="Vías de transmisión" items={[...o.transmissionRoute,o.vector&&`Vector: ${o.vector}`]}/></div><Facts title="Prevención y control" items={o.prevention}/></>}
            {s.id==='cycle'&&<>{!!o.parasiticStages?.length&&<ParasiteStageVisualizer stages={o.parasiticStages!} parasiteName={o.scientificName}/>} {!!supplement?.cycles.length&&<button onClick={()=>onOpen('ciclo')} className="rounded-xl border border-emerald-200 bg-white p-4 text-sm font-semibold text-emerald-900">Consultar el ciclo original CDC, fase infectiva y fase diagnóstica <ChevronDown className="inline" size={15}/></button>}</>}
            {s.id==='guatemala'&&<><dl className="grid grid-cols-2 gap-4 rounded-xl border border-slate-200 bg-white p-4"><div><dt className="text-xs text-slate-500">Situación registrada</dt><dd className="mt-1 text-sm font-semibold">{o.guatemalaRelevance.endemicStatus}</dd></div><div><dt className="text-xs text-slate-500">Prioridad registrada</dt><dd className="mt-1 text-sm font-semibold">{o.guatemalaRelevance.priorityLevel}</dd></div></dl><Facts title="Contexto del registro" items={[o.guatemalaRelevance.officialNotes,o.guatemalaRelevance.notificationGroup]}/><Facts title="Departamentos mencionados en el registro" items={o.guatemalaRelevance.departmentsWithHighPrevalence}/><p className="text-xs leading-6 text-slate-500">Las referencias regionales se identifican por su origen. La información guardada requiere contrastar el periodo y la fuente nacional antes de interpretarse como situación actual de Guatemala.</p>{o.scientificName==='Onchocerca volvulus'&&<p className="rounded-xl border border-sky-200 bg-white p-4 text-sm leading-7">Guatemala fue certificada libre de transmisión de oncocercosis en 2016. <a href="https://www.paho.org/es/noticias/26-9-2016-guatemala-es-cuarto-pais-mundo-eliminar-oncocercosis" target="_blank" rel="noopener noreferrer" className="underline text-sky-800">Comunicado de la OPS</a>.</p>}<RegionalReferences/></>}
            {s.id==='sources'&&<><p className="text-xs text-slate-500">Última revisión registrada: {o.lastReviewedDate}. El estado guardado de la ficha no verifica automáticamente los fragmentos nuevos.</p>{o.bibliography.map((b,i)=><article key={i} className="rounded-xl border border-slate-200 bg-white p-4 text-sm"><p className="font-semibold text-slate-900">{b.source}</p>{safeHttpsUrl(b.url)?<a href={safeHttpsUrl(b.url)} target="_blank" rel="noopener noreferrer" className="mt-1 block text-sky-800 underline">{b.title}</a>:<p className="mt-1">{b.title}</p>}<p className="mt-2 text-xs text-slate-500">Edición guardada: {b.year} · {b.status}{b.consultedAt&&` · Consultada: ${b.consultedAt}`}</p></article>)}<button onClick={()=>onOpen('documentos')} className="text-sm font-semibold text-sky-800 underline">Abrir el lector de páginas completas</button></>}
          </>}
          <Excerpts key={`${o.id}-${s.id}-${q}`} entries={entries}/>
          {o.documentIndexed&&!entries.length&&!['guatemala','sources'].includes(s.id)&&<p className="text-sm leading-6 text-slate-500">No se identificó un fragmento bajo este tema. El lector de páginas originales conserva todo el texto vinculado, incluso cuando el documento no contiene un encabezado reconocible.</p>}
        </section>;})}
      </div>
    </div>
  </div>;
}
