import type { Microorganism } from '../types/microorganism';
import { learningSupplement } from '../services/learningAtlas';
import { RegionalReferences } from './RegionalReferences';
function Facts({title,items}:{title:string;items:string[]}) {return <div className="rounded-lg border border-slate-200 p-3 text-sm"><h4 className="font-semibold">{title}</h4>{items.length?<ul className="mt-2 list-disc pl-5 space-y-1">{items.map((s,i)=><li key={i}>{s}</li>)}</ul>:<p className="mt-2 text-xs text-slate-500">Pendiente de documentar en esta ficha.</p>}</div>;}
export function AdditionalRecordDetails({organism,section}:{organism:Microorganism;section:string}) {
  const shows=(s:string)=>section==='all'||section===s;
  const m=organism.microbiologyCharacteristics;
  const supplement=learningSupplement(organism);
  return <>
    {shows('taxonomia')&&<section className="space-y-3"><h3 className="font-bold">Microbiología y estructuras</h3><div className="grid gap-3 sm:grid-cols-2"><Facts title="Características de crecimiento" items={[m.metabolism&&`Metabolismo: ${m.metabolism}`,m.optimalTemp&&`Temperatura: ${m.optimalTemp}`,m.growthTime&&`Tiempo de crecimiento: ${m.growthTime}`].filter((s):s is string=>!!s)}/><Facts title="Medios de cultivo documentados" items={m.cultureMedia??[]}/><Facts title="Pruebas bioquímicas" items={m.keyBiochemicalTests??[]}/><Facts title="Estructuras externas e internas" items={organism.externalAndInternalStructures}/></div></section>}
    {shows('virulencia')&&<div className="grid gap-3 sm:grid-cols-2"><Facts title="Reservorios" items={organism.reservoir}/><Facts title="Vías de transmisión" items={[...organism.transmissionRoute,...(organism.vector?[`Vector registrado: ${organism.vector}`]:[])]}/></div>}
    {shows('diagnostico')&&<section className="space-y-3"><Facts title="Hallazgos de laboratorio guardados" items={organism.labFindings}/>{supplement&&<div className="rounded-lg border border-sky-200 bg-sky-50 p-4"><h4 className="font-bold">Claves de interpretación · fuentes documentadas</h4><ul className="mt-2 list-disc pl-5 space-y-2 text-sm">{supplement.diagnosticPearls.map(s=><li key={s}>{s}</li>)}</ul><p className="mt-3 text-xs">Síntesis educativa pendiente de revisión clínica. La galería y los ciclos enlazan las fuentes originales.</p></div>}</section>}
    {shows('tratamiento')&&<div className="grid gap-3 sm:grid-cols-2"><Facts title="Prevención" items={organism.prevention}/><Facts title="Contraindicaciones y alertas guardadas" items={organism.treatment.contraindicationsOrAlerts??[]}/></div>}
    {shows('guatemala')&&<><p className="rounded-lg bg-amber-50 p-3 text-xs text-amber-900">La información epidemiológica guardada necesita contrastarse con fuentes nacionales y su periodo. Una ficha o imagen del CDC no demuestra circulación actual en Guatemala.</p>{organism.scientificName==='Onchocerca volvulus'&&<p className="rounded-lg border border-sky-200 bg-sky-50 p-4 text-sm">La OPS documentó la certificación de Guatemala como país libre de transmisión de oncocercosis en 2016. Estudiar este parásito no implica que exista transmisión activa nacional. <a className="underline text-sky-800" target="_blank" rel="noopener noreferrer" href="https://www.paho.org/es/noticias/26-9-2016-guatemala-es-cuarto-pais-mundo-eliminar-oncocercosis">Comunicado OPS · 26/09/2016</a></p>}<RegionalReferences/></>}
  </>;
}
