import {useState} from 'react';
import type {ExtractionProposal} from '../types/academicLibrary';
import type {Microorganism} from '../types/microorganism';
import {DOCUMENT_SECTION_LABELS,documentBlocks,type DocumentPageLink,type DocumentSection} from '../services/documentAtlas';
export function DocumentEvidencePanel({organism,pages,proposals,onReview}:{organism:Microorganism;pages:DocumentPageLink[];proposals:ExtractionProposal[];onReview?:(id:string)=>void}){
  const [section,setSection]=useState<DocumentSection>('all'),[query,setQuery]=useState(''),[documentId,setDocumentId]=useState('all'),[limit,setLimit]=useState(12);
  const documents=Array.from(new Map(pages.map(p=>[p.document.id,p.document])).values());
  const filtered=pages.filter(p=>(documentId==='all'||p.document.id===documentId)&&(section==='all'||documentBlocks(p.text).some(b=>b.section===section))&&p.text.toLocaleLowerCase('es').includes(query.trim().toLocaleLowerCase('es')));
  const related=proposals.filter(p=>p.targetMicroorganismId===organism.id&&p.status!=='descartado');
  return <section className="space-y-4"><header className="rounded-xl border border-sky-200 bg-sky-50 p-4 space-y-2"><h3 className="font-bold text-xl">Información de tus documentos · {pages.length} páginas vinculadas</h3><p className="text-sm">Texto que ya cargaste, con documento y página de origen. Se organiza por temas dentro de cada página y se conserva completo. Las páginas con varios agentes muestran ese contexto; las continuaciones señalan el epígrafe usado para vincularlas.</p><p className="text-xs text-slate-600">La clasificación temática ayuda a estudiar. La revisión comprueba que el fragmento se haya atribuido al microorganismo y al campo correctos; el estado de una propuesta no oculta el texto del documento.</p>{organism.originalCategory&&<p className="text-xs font-semibold text-amber-900">La categoría de consulta se corrigió a {organism.category}. El registro original conservaba {organism.originalCategory}; tus datos guardados se mantienen para la revisión y el respaldo.</p>}</header>
    <div className="grid gap-3 sm:grid-cols-3"><label className="text-sm">Tema<select className="mt-1 w-full rounded border p-2" value={section} onChange={e=>{setSection(e.target.value as DocumentSection);setLimit(12);}}>{Object.entries(DOCUMENT_SECTION_LABELS).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label className="text-sm">Documento<select className="mt-1 w-full rounded border p-2" value={documentId} onChange={e=>{setDocumentId(e.target.value);setLimit(12);}}><option value="all">Todos ({documents.length})</option>{documents.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select></label><label className="text-sm">Buscar en el texto<input className="block mt-1 w-full rounded border p-2" value={query} onChange={e=>{setQuery(e.target.value);setLimit(12);}} placeholder="Tinción, muestra, síntomas…"/></label></div>
    {!!related.length&&<details className="rounded-lg border border-emerald-200 p-3 text-sm"><summary className="font-semibold cursor-pointer">Fragmentos revisados y propuestas vinculadas ({related.length})</summary>{related.map(p=><article key={p.id} className="mt-3 border-t pt-3 space-y-2"><p className="font-semibold">{p.field} · {p.status==='pendiente'?'Pendiente de revisión':'Revisado por usuario'}</p><p className="text-xs">{p.documentTitle} · página {p.sourcePage}</p><p>{p.userEditedSnippet??p.proposedValue}</p>{p.status==='pendiente'&&onReview&&<button className="text-sky-800 underline" onClick={()=>onReview(p.documentId)}>Abrir revisión</button>}</article>)}</details>}
    {!filtered.length&&<p className="rounded-lg border border-dashed p-5 text-sm">{pages.length?'No hay páginas para este filtro. Prueba otro tema o busca una palabra.':'No se encontró texto vinculado a este nombre. Consulta la biblioteca: algunas páginas son imágenes sin texto y otras usan nombres que todavía no se reconocen.'}</p>}
    {filtered.slice(0,limit).map(p=><article key={`${p.document.id}-${p.pageNumber}`} className="rounded-xl border border-slate-200 bg-white overflow-hidden"><header className="bg-slate-50 p-4 space-y-1"><h4 className="font-semibold">{p.document.title} · página {p.pageNumber}</h4><p className="text-xs text-slate-600">{p.document.authorOrInstitution} · edición guardada: {p.document.yearOrEdition} · {p.document.sourceTier}</p><p className="text-xs font-semibold text-sky-800">{Array.from(new Set(documentBlocks(p.text).map(b=>DOCUMENT_SECTION_LABELS[b.section]))).join(' · ')} · {p.association==='direct'?'Nombre reconocido en esta página':`Continuación del epígrafe de página ${p.headingPage}; revisar contexto`}</p>{p.mentionedNames.length>1&&<p className="text-xs text-amber-900">Esta página menciona varios agentes: {p.mentionedNames.join(', ')}. Su contenido no se atribuye íntegramente a una sola especie.</p>}</header><div className="p-4"><div className="space-y-4">{documentBlocks(p.text).filter(b=>section==='all'||b.section===section).map(b=><section key={b.start}><h5 className="mb-1 text-sm font-semibold text-sky-900">{DOCUMENT_SECTION_LABELS[b.section]}</h5><p className="whitespace-pre-wrap break-words text-sm leading-relaxed">{b.text.length>1800?b.text.slice(0,1800)+'…':b.text}</p></section>)}</div>{p.text.length>1800&&<details className="mt-3 text-sm"><summary className="cursor-pointer text-sky-800 underline">Leer texto completo de la página</summary><p className="mt-3 whitespace-pre-wrap break-words leading-relaxed">{p.text}</p></details>}</div></article>)}
    {filtered.length>limit&&<button className="rounded-lg border p-3 text-sm" onClick={()=>setLimit(v=>v+12)}>Ver otras 12 páginas ({filtered.length-limit} restantes)</button>}
  </section>;
}
