import {useMemo,useState} from 'react';
import type {Microorganism} from '../types/microorganism';
import {EvidenceRegister,EVIDENCE_COUNTRIES,resistancePercent,type EvidenceKind,type EvidenceRecord} from '../services/evidenceRegister';
import {LiveSearchPanel} from './LiveSearchPanel';
import {RegionalReferences} from './RegionalReferences';
const common=[['organism','Microorganismo'],['title','Título del documento'],['publisher','Institución / autores'],['sourceUrl','Enlace HTTPS de la fuente'],['sourceDate','Fecha de publicación de la fuente'],['sourceLocator','Página, tabla o sección'],['population','Población, territorio y contexto'],['summary','Síntesis de la evidencia']] as const;
const amr=[['drug','Antimicrobiano'],['specimen','Tipo de muestra / aislamientos'],['periodStart','Inicio del periodo'],['periodEnd','Fin del periodo'],['standard','Método y norma (CLSI / EUCAST / otra)'],['standardVersion','Versión de la norma'],['tested','Aislamientos evaluados'],['resistant','Aislamientos resistentes']] as const;
const treatment=[['version','Versión / edición de la guía']] as const;
function download(name:string,value:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function EvidenceRadar({kind,microorganisms,onSelectOrganism}:{kind:EvidenceKind;microorganisms:Microorganism[];onSelectOrganism:(o:Microorganism)=>void}) {
  const repo=useMemo(()=>new EvidenceRegister(),[]);
  const [revision,setRevision]=useState(0),[tab,setTab]=useState<'records'|'pubmed'|'sources'>('records'),[form,setForm]=useState<Record<string,string>>({country:'Guatemala'}),[showForm,setShowForm]=useState(false),[country,setCountry]=useState('Guatemala'),[status,setStatus]=useState('all'),[message,setMessage]=useState(''),[error,setError]=useState(''),[reviewId,setReviewId]=useState(''),[reviewer,setReviewer]=useState(''),[note,setNote]=useState('');
  let records:EvidenceRecord[]=[],readError='';try{records=repo.read().filter(r=>r.kind===kind);}catch(e){readError=(e as Error).message;}
  void revision;
  const visible=records.filter(r=>(country==='all'||r.country===country)&&(status==='all'||r.review===status));
  const mutate=(action:()=>string)=>{setError('');setMessage('');try{setMessage(action());setRevision(v=>v+1);}catch(e){setError((e as Error).message);}};
  const submit=()=>mutate(()=>{const input:Record<string,unknown>={...form,kind};if(kind==='amr'){input.tested=form.tested?.trim()?Number(form.tested):null;input.resistant=form.resistant?.trim()?Number(form.resistant):null;}
    const result=repo.add([input]);setForm({country:'Guatemala'});setShowForm(false);return `${result.added} registro agregado; ${result.duplicates} duplicados omitidos. Pendiente de revisión.`;});
  return <section className="space-y-4"><header className="rounded-xl border border-sky-200 bg-sky-50 p-5 space-y-2"><p className="text-xs font-bold text-sky-800">GUATEMALA PRIMERO · REGISTRO CON REVISIÓN</p><h3 className="font-bold text-2xl">{kind==='amr'?'AMR Radar':'Treatment Tracker'}</h3><p className="text-sm">{kind==='amr'?'Registra resultados agregados de resistencia por especie, antimicrobiano, muestra, periodo y método. Cada fuente conserva su propio denominador; no se promedian series diferentes.':'Conserva versiones de guías, su población y el país de origen. La evidencia se revisa antes de considerarla para una ficha; una publicación reciente no modifica un tratamiento automáticamente.'}</p><p className="text-xs text-slate-600">Registros locales incluidos en el respaldo general. Sin datos precargados de vigilancia. «Revisado por usuario» identifica una decisión local, no una aprobación clínica independiente.</p></header>
    <nav aria-label="Opciones de evidencia" className="flex flex-wrap gap-2">{([['records','Registro de fuentes'],['pubmed','Buscar evidencia PubMed'],['sources','Fuentes regionales']] as const).map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)} className={`rounded-lg border px-3 py-2 text-sm ${tab===id?'bg-slate-900 text-white':'bg-white'}`}>{label}</button>)}</nav>
    {tab==='pubmed'&&<LiveSearchPanel initialTopic={kind==='amr'?'resistance':'treatment'} microorganisms={microorganisms} onSelectOrganism={onSelectOrganism}/>}
    {tab==='sources'&&<><div className="flex flex-wrap gap-3 text-sm text-sky-800 underline">{kind==='amr'?<><a href="https://www.paho.org/es/ram-portal" target="_blank" rel="noopener noreferrer">OPS · portal de resistencia</a><a href="https://opendata.paho.org/es/datos-de-resistencia-los-antimicrobianos" target="_blank" rel="noopener noreferrer">OPS · datos y metodología</a></>:<a href="https://www.paho.org/es/documentos/directrices-para-diagnostico-clinico-tratamiento-dengue-chikunguna-zika-ops-2022" target="_blank" rel="noopener noreferrer">OPS · guía regional de dengue, chikunguña y zika (2022)</a>}</div><RegionalReferences/></>}
    {tab==='records'&&<>
      {(readError||error)&&<p role="alert" className="rounded-lg bg-rose-50 p-3 text-sm text-rose-900">{readError||error}</p>}{message&&<p role="status" className="rounded-lg bg-emerald-50 p-3 text-sm">{message}</p>}
      <div className="flex flex-wrap gap-3"><button disabled={!!readError} className="rounded-lg bg-sky-800 px-4 py-2 text-white text-sm" onClick={()=>setShowForm(!showForm)}>{showForm?'Cerrar formulario':'Agregar fuente'}</button><label className="rounded-lg border p-2 text-sm cursor-pointer">Importar registros JSON<input type="file" accept="application/json,.json" className="sr-only" disabled={!!readError} onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setError('');try{if(file.size>250000)throw new Error('El archivo supera 250 KB.');const values:unknown=JSON.parse(await file.text());if(!Array.isArray(values)||values.some(v=>v?.kind!==kind))throw new Error('Importa una lista de registros del módulo seleccionado.');mutate(()=>{const r=repo.add(values);return `${r.added} registros agregados pendientes de revisión; ${r.duplicates} duplicados omitidos.`;});}catch(ex){setError((ex as Error).message);}}}/></label><button className="rounded-lg border p-2 text-sm" disabled={!!readError||!records.length} onClick={()=>mutate(()=>{download(`infectoatlas-${kind}-fuentes.json`,repo.exportInputs(kind));return 'Exportación preparada. Las decisiones de revisión se conservan en el respaldo general; una importación entra pendiente de revisión.';})}>Exportar fuentes JSON</button></div>
      {showForm&&<form onSubmit={e=>{e.preventDefault();submit();}} className="rounded-xl border border-slate-200 bg-white p-4 space-y-4"><h4 className="font-bold">Nueva fuente documentada</h4><p className="text-xs">Completa datos de la fuente original. No introduzcas información de pacientes. Para agregar una nueva versión, elige el registro anterior y conserva ambas fuentes.</p><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">País de la fuente<select value={form.country} onChange={e=>setForm({...form,country:e.target.value})} className="mt-1 block w-full rounded border p-2">{EVIDENCE_COUNTRIES.map(c=><option key={c}>{c}</option>)}</select></label>{[...common,...(kind==='amr'?amr:treatment)].map(([field,label])=><label key={field} className="text-sm">{label}{field==='summary'||field==='population'?<textarea required maxLength={field==='summary'?700:350} value={form[field]??''} onChange={e=>setForm({...form,[field]:e.target.value})} className="mt-1 block w-full rounded border p-2"/>:<input required list={field==='organism'?`species-${kind}`:undefined} type={['sourceDate','periodStart','periodEnd'].includes(field)?'date':['tested','resistant'].includes(field)?'number':field==='sourceUrl'?'url':'text'} min={field==='tested'?1:0} step={1} maxLength={field==='sourceUrl'?1200:240} value={form[field]??''} onChange={e=>setForm({...form,[field]:e.target.value})} className="mt-1 block w-full rounded border p-2"/>}</label>)}{kind==='treatment'&&<label className="text-sm">Versión anterior (opcional)<select className="mt-1 block w-full rounded border p-2" value={form.supersedes??''} onChange={e=>setForm({...form,supersedes:e.target.value})}><option value="">Primera versión registrada</option>{records.map(r=><option key={r.id} value={r.id}>{r.organism} · {r.country} · {r.version}</option>)}</select></label>}</div><datalist id={`species-${kind}`}>{microorganisms.map(o=><option key={o.id} value={o.scientificName}/>)}</datalist><button className="rounded-lg bg-sky-800 px-4 py-2 text-sm text-white">Guardar pendiente de revisión</button></form>}
      <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">País<select value={country} onChange={e=>setCountry(e.target.value)} className="block mt-1 w-full rounded border p-2"><option value="all">Todos los países · registros separados</option>{EVIDENCE_COUNTRIES.map(c=><option key={c}>{c}</option>)}</select></label><label className="text-sm">Revisión<select className="block mt-1 w-full rounded border p-2" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Todos</option><option value="pending">Pendiente</option><option value="accepted">Revisado por usuario</option><option value="rejected">Descartado por usuario</option></select></label></div>
      {!visible.length&&<p className="rounded-xl border border-dashed p-6 text-sm text-slate-600">No hay registros para este filtro. Esto significa ausencia de datos registrados, no ausencia de resistencia ni de enfermedad en Guatemala.</p>}
      {visible.map(r=><article key={r.id} className="rounded-xl border border-slate-200 bg-white p-4 space-y-3"><div className="flex flex-wrap justify-between gap-3"><h4 className="font-bold">{r.organism} · {kind==='amr'?r.drug:r.version}</h4><span className={`rounded px-2 py-1 text-xs ${r.review==='accepted'?'bg-emerald-50 text-emerald-900':'bg-amber-50 text-amber-900'}`}>{r.review==='accepted'?'Revisado por usuario':r.review==='rejected'?'Descartado por usuario':'Pendiente de revisión'}</span></div><p className="text-xs font-semibold text-sky-800">{r.country} · {r.population}</p><a href={r.sourceUrl} target="_blank" rel="noopener noreferrer" className="text-sm text-sky-800 underline">{r.title}</a><p className="text-xs text-slate-600">{r.publisher} · Fuente: {r.sourceDate} · {r.sourceLocator}</p>
        {kind==='amr'&&<div className="space-y-2 text-sm"><p>{r.resistant} resistentes / {r.tested} aislamientos evaluados · {r.specimen}</p><p className="text-xs">Periodo: {r.periodStart} a {r.periodEnd} · {r.standard} {r.standardVersion}</p>{r.review==='accepted'?<><p className="font-semibold">{resistancePercent(r)?.toFixed(1)} % resistentes entre los aislamientos de esta fuente</p><div className="h-3 rounded bg-slate-100" role="img" aria-label={`${resistancePercent(r)?.toFixed(1)} por ciento resistentes`}><div className="h-3 rounded bg-sky-700" style={{width:`${resistancePercent(r)}%`}}/></div><p className="text-xs">No es prevalencia poblacional ni predice el resultado de un paciente.</p></>:<p className="text-xs text-amber-900">Porcentaje del radar oculto hasta revisar la fuente y el denominador.</p>}</div>}
        <p className="text-sm">{r.summary}</p>{r.supersedes&&<p className="text-xs">Versión anterior: {records.find(v=>v.id===r.supersedes)?.version??r.supersedes}. El registro anterior se conserva; revisa vigencia y diferencias.</p>}
        <div className="flex flex-wrap gap-3"><button className="text-sm text-sky-800 underline" onClick={()=>{setReviewId(reviewId===r.id?'':r.id);setNote('');}}>Revisar fuente</button>{microorganisms.filter(o=>o.scientificName.toLowerCase()===r.organism.toLowerCase()).map(o=><button key={o.id} onClick={()=>onSelectOrganism(o)} className="text-sm text-sky-800 underline">Abrir ficha vinculada</button>)}</div>
        {reviewId===r.id&&<form className="rounded-lg bg-slate-50 p-3 space-y-3" onSubmit={e=>e.preventDefault()}><label className="block text-sm">Nombre del revisor<input value={reviewer} onChange={e=>setReviewer(e.target.value)} className="block w-full border rounded p-2" maxLength={120}/></label><label className="block text-sm">Nota: método, limitaciones y adecuación a Guatemala<textarea value={note} onChange={e=>setNote(e.target.value)} className="block w-full border rounded p-2" maxLength={700}/></label><div className="flex flex-wrap gap-3">{(['accepted','rejected'] as const).map(decision=><button key={decision} className="rounded border p-2 text-sm" onClick={()=>mutate(()=>{repo.review(r.id,decision,reviewer,note);setReviewId('');return 'Decisión y nota añadidas al historial de revisión.';})}>{decision==='accepted'?'Registrar revisión favorable':'Descartar esta fuente'}</button>)}</div></form>}
        {!!r.reviews.length&&<details className="text-xs"><summary className="cursor-pointer font-semibold">Historial de revisión ({r.reviews.length})</summary>{r.reviews.map((v,i)=><p className="mt-2 border-t pt-2" key={i}>{v.at} · {v.reviewer} · {v.decision==='accepted'?'Revisión favorable':'Descartado'}<br/>{v.note}</p>)}</details>}
      </article>)}
    </>}
  </section>;
}
