import {lazy,Suspense,useEffect,useMemo,useState} from 'react';
import {EXPERIMENTAL_STRUCTURE,loadExperimentalStructure,type ProteinTrace} from '../services/experimentalStructure';
import type {ModelProfile} from '../data/modelProfiles';
const MicrobeScene=lazy(()=>import('./MicrobeScene'));
export function ExperimentalLab(){
  const [trace,setTrace]=useState<ProteinTrace|null>(null),[error,setError]=useState(''),[attempt,setAttempt]=useState(0);
  useEffect(()=>{const controller=new AbortController();let active=true;const timeout=setTimeout(()=>controller.abort(),20000);setTrace(null);setError('');loadExperimentalStructure(controller.signal).then(value=>{if(active)setTrace(value);}).catch(()=>{if(active)setError('No se pudieron cargar las coordenadas experimentales de RCSB. Reintenta o consulta su visor original. No se muestra un modelo inventado en su lugar.');}).finally(()=>clearTimeout(timeout));return()=>{active=false;clearTimeout(timeout);controller.abort();};},[attempt]);
  const profile=useMemo<ModelProfile>(()=>({kind:'virus',title:EXPERIMENTAL_STRUCTURE.title,scope:EXPERIMENTAL_STRUCTURE.scope,sourceUrl:EXPERIMENTAL_STRUCTURE.sourceUrl,parts:[['surface','Cadena A','#38bdf8'],['genome','Cadena B','#fbbf24'],['appendages','Cadena C','#a78bfa']]}),[]);
  return <section className="space-y-4"><header className="rounded-2xl border border-sky-200 bg-white p-5"><p className="text-[10px] font-bold uppercase tracking-widest text-sky-800">Estructura experimental publicada · PDB 6VXX</p><h2 className="mt-2 text-xl font-semibold">3D basado en coordenadas reales</h2><p className="mt-3 text-sm leading-7">Se descargan automáticamente las coordenadas de RCSB PDB y se dibuja la traza proteica. {EXPERIMENTAL_STRUCTURE.scope}</p><p className="mt-3 text-xs text-slate-500">{EXPERIMENTAL_STRUCTURE.method} · resolución informada: {EXPERIMENTAL_STRUCTURE.resolution} · datos públicos de referencia</p></header>
    {!trace&&!error&&<p role="status" className="rounded-xl border p-5 text-sm">Cargando coordenadas experimentales desde RCSB…</p>}{error&&<div role="alert" className="space-y-3 rounded-xl border border-amber-200 bg-amber-50 p-5 text-sm"><p>{error}</p><button className="font-semibold text-sky-800 underline" onClick={()=>setAttempt(n=>n+1)}>Reintentar carga</button></div>}
    {trace&&<><p className="text-xs text-slate-500">{trace.atomCount} carbonos alfa leídos · {trace.chains.length} cadenas · huecos del depósito conservados</p><Suspense fallback={<p role="status">Preparando estructura…</p>}><MicrobeScene key={attempt} profile={profile} structure={trace}/></Suspense><details className="rounded-xl border border-slate-200 bg-white p-4 text-xs text-slate-500"><summary className="cursor-pointer font-semibold">Trazabilidad de las coordenadas</summary><p className="mt-3 break-all">Archivo: {EXPERIMENTAL_STRUCTURE.coordinateUrl}</p><p className="mt-2 break-all">SHA-256: {trace.sha256}</p><p className="mt-2">Recuperado: {trace.retrievedAt}</p></details></>}
    <footer className="space-y-2 rounded-xl border border-slate-200 bg-white p-4 text-sm leading-7"><p>Coordenadas: RCSB PDB / wwPDB · PDB 6VXX. Visualización de InfectoAtlas GT mediante Three.js.</p><p>{EXPERIMENTAL_STRUCTURE.publication} · <a href={EXPERIMENTAL_STRUCTURE.publicationUrl} target="_blank" rel="noopener noreferrer" className="text-sky-800 underline">Publicación de la estructura</a></p><div className="flex flex-wrap gap-4"><a href={EXPERIMENTAL_STRUCTURE.sourceUrl} target="_blank" rel="noopener noreferrer" className="text-sky-800 underline">Depósito y validación</a><a href="https://www.rcsb.org/3d-view/6VXX" target="_blank" rel="noopener noreferrer" className="text-sky-800 underline">Visor molecular original</a><a href={EXPERIMENTAL_STRUCTURE.licenseUrl} target="_blank" rel="noopener noreferrer" className="text-sky-800 underline">Políticas de uso y cita</a></div></footer>
  </section>;
}
