const references = [
  {country:'Guatemala',publisher:'MSPAS',title:'Portal del Ministerio de Salud Pública',url:'https://www.mspas.gob.gt/',scope:'Fuente nacional prioritaria. Comprueba el documento, periodo y departamento antes de registrar cifras.'},
  {country:'Guatemala',publisher:'OPS',title:'Perfil de salud de Guatemala',url:'https://hia.paho.org/es/perfiles-de-pais/guatemala',scope:'Contexto nacional publicado por la OPS. Cada indicador conserva su año y método; no representa datos en tiempo real.'},
  {country:'México · referencia vecina',publisher:'Secretaría de Salud / Dirección General de Epidemiología',title:'Manuales para la vigilancia epidemiológica',url:'https://www.gob.mx/salud/documentos/manuales-para-la-vigilancia-epidemiologica-102563',scope:'Referencia metodológica de México. La versión y las definiciones se comprueban en cada manual. No constituye una norma del MSPAS.'},
  {country:'Américas · referencia regional',publisher:'OPS / ReLAVRA+',title:'Red de vigilancia de resistencia antimicrobiana',url:'https://www.paho.org/es/temas/resistencia-antimicrobianos/red-latinoamericana-caribe-vigilancia-resistencia-antimicrobianos',scope:'Guatemala participa en la red. Los datos de otros países se mantienen separados y requieren métodos y denominadores comparables.'},
  {country:'Américas · referencia regional',publisher:'OPS',title:'Directrices para diagnóstico y tratamiento de dengue, chikunguña y zika · 2022',url:'https://www.paho.org/es/documentos/directrices-para-diagnostico-clinico-tratamiento-dengue-chikunguna-zika-ops-2022',scope:'Guía regional de 2022. Se necesita revisar su vigencia y adecuación clínica a Guatemala antes de incorporar recomendaciones.'},
];
export function RegionalReferences() {
  return <section className="space-y-3"><h3 className="font-bold text-lg">Guatemala primero · referencias nacionales y regionales</h3><p className="text-sm text-slate-600">Las fuentes vecinas amplían el contexto cuando falta documentación nacional. El país, la población y el periodo de cada fuente se conservan: sus cifras no se trasladan a Guatemala.</p><div className="grid gap-3 sm:grid-cols-2">{references.map(r=><article key={r.url} className="rounded-xl border border-slate-200 bg-white p-4 space-y-2 text-sm"><p className="text-xs font-bold text-sky-800">{r.country} · {r.publisher}</p><a href={r.url} target="_blank" rel="noopener noreferrer" className="font-semibold text-sky-800 underline">{r.title}</a><p className="text-xs text-slate-600">{r.scope}</p><p className="text-xs text-slate-500">Enlace consultado: 03/10/2026</p></article>)}</div></section>;
}
