import {useMemo,useState} from 'react';
import {Microscope,ZoomIn,ZoomOut,RotateCcw,ArrowLeft,ArrowRight,ArrowUp,ArrowDown,BookOpen} from 'lucide-react';
import type {Microorganism} from '../types/microorganism';
import {buildSpecimenCollection,SPECIMEN_LABELS,type SpecimenKind,type SpecimenImage} from '../services/specimenLab';
import {learningSupplement} from '../services/learningAtlas';
import {safeHttpsUrl} from './SourceImageGallery';
import {CdcAttribution} from './CdcAttribution';
function SlideViewer({entry}:{entry:SpecimenImage}){
  const [zoom,setZoom]=useState(1),[position,setPosition]=useState({x:0,y:0}),[failed,setFailed]=useState(false),[ready,setReady]=useState(false),[showClues,setShowClues]=useState(true);
  const pearls=learningSupplement(entry.organism)?.diagnosticPearls??[];
  const move=(x:number,y:number)=>setPosition(p=>({x:Math.max(-45,Math.min(45,p.x+x)),y:Math.max(-45,Math.min(45,p.y+y))}));
  return <article className="overflow-hidden rounded-2xl border border-slate-700 bg-slate-950 text-slate-200"><header className="space-y-2 border-b border-slate-800 p-5"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-sky-300">Preparación de referencia · imagen real</p><h3 className="text-lg font-semibold italic">{entry.organism.scientificName}</h3><p className="text-sm text-slate-300">{entry.image.caption}</p><p className="text-xs text-slate-400">{entry.preparation} · {entry.image.stainOrModality}</p></header>
    <div className="relative flex h-80 items-center justify-center overflow-hidden bg-black sm:h-[440px]">{!failed&&safeHttpsUrl(entry.image.url)?<img src={safeHttpsUrl(entry.image.url)} alt={entry.image.caption} referrerPolicy="no-referrer" onLoad={()=>setReady(true)} onError={()=>setFailed(true)} className="h-full w-full object-contain" style={{transform:`translate(${position.x}%,${position.y}%) scale(${zoom})`}}/>:<p role="alert" className="p-6 text-sm">La fuente no cargó la imagen. El enlace original sigue disponible; no se sustituye por una imagen generada.</p>}{!ready&&!failed&&<p role="status" className="absolute rounded-lg bg-slate-900/90 p-3 text-xs">Cargando microfotografía original…</p>}</div>
    <div className="space-y-4 p-5"><div className="flex flex-wrap gap-2">{[[ZoomIn,'Ampliar',()=>setZoom(z=>Math.min(4,z+.5))],[ZoomOut,'Reducir',()=>setZoom(z=>Math.max(1,z-.5))],[RotateCcw,'Restablecer',()=>{setZoom(1);setPosition({x:0,y:0});}],[ArrowLeft,'Mover izquierda',()=>move(5,0)],[ArrowRight,'Mover derecha',()=>move(-5,0)],[ArrowUp,'Mover arriba',()=>move(0,5)],[ArrowDown,'Mover abajo',()=>move(0,-5)]] .map(([Icon,label,action])=>{const Control=Icon as typeof ZoomIn;return <button key={label as string} aria-label={label as string} title={label as string} onClick={action as ()=>void} disabled={!ready||failed} className="rounded-lg border border-slate-700 bg-slate-900 p-2.5 hover:bg-slate-800 disabled:opacity-40"><Control size={17}/></button>;})}<span className="self-center text-xs text-slate-400">Zoom digital {zoom.toFixed(1)}×</span></div><p className="text-xs leading-5 text-slate-400">La ampliación es digital, no una magnificación óptica calibrada. No se altera la tinción ni se añade detalle a la imagen.</p>
      <button className="text-sm font-semibold text-sky-300" aria-expanded={showClues} onClick={()=>setShowClues(v=>!v)}>{showClues?'Ocultar':'Mostrar'} guía de observación</button>{showClues&&<section className="space-y-3 rounded-xl border border-slate-800 bg-slate-900 p-4"><h4 className="text-sm font-semibold">Qué estudiar en esta preparación</h4><p className="text-sm leading-6">{entry.image.interpretation}</p>{pearls.length>0&&<ul className="list-disc space-y-2 pl-5 text-xs leading-6 text-slate-300">{pearls.map(p=><li key={p}>{p}</li>)}</ul>}<p className="text-xs text-slate-400">Las claves describen la especie o grupo de referencia; no son marcas de objetos detectados automáticamente en esta fotografía.</p></section>}
      <footer className="space-y-2 border-t border-slate-800 pt-4 text-xs leading-6 text-slate-400"><p>{entry.image.creditOrSource}</p><p>{entry.image.license} · Imagen: {entry.image.imageDate??'fecha no informada'} · Consultada: {entry.image.consultedAt??'no informada'}</p><div className="flex flex-wrap gap-4"><a href={safeHttpsUrl(entry.image.sourceUrl)} target="_blank" rel="noopener noreferrer" className="text-sky-300 underline">Registro y descripción original</a><a href={safeHttpsUrl(entry.image.url)} target="_blank" rel="noopener noreferrer" className="text-sky-300 underline">Abrir imagen original</a><a href={safeHttpsUrl(entry.image.licenseUrl)} target="_blank" rel="noopener noreferrer" className="text-sky-300 underline">Condiciones de uso</a></div></footer>
    </div>
  </article>;
}
export function SpecimenLab({microorganisms=[],onSelectOrganism}:{microorganisms?:Microorganism[];onSelectOrganism?:(o:Microorganism)=>void}){
  const collection=useMemo(()=>buildSpecimenCollection(microorganisms),[microorganisms]);
  const [kind,setKind]=useState<SpecimenKind|'all'>('blood'),[query,setQuery]=useState(''),[selectedId,setSelectedId]=useState(''),[compareId,setCompareId]=useState('');
  const filtered=collection.filter(e=>(kind==='all'||e.specimen===kind)&&`${e.organism.scientificName} ${e.image.caption} ${e.image.stainOrModality}`.toLocaleLowerCase('es').includes(query.toLocaleLowerCase('es').trim()));
  const selected=filtered.find(e=>e.id===selectedId)??filtered[0],comparison=filtered.find(e=>e.id===compareId&&e.id!==selected?.id);
  return <section className="space-y-5"><header className="rounded-2xl bg-slate-900 p-6 text-white"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-sky-300">Laboratorio virtual · muestras reales</p><h2 className="mt-2 text-2xl font-semibold">Microscopía de sangre, tejidos y cultivos</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-slate-300">Estudia preparaciones de referencia publicadas por el CDC. El laboratorio reúne las imágenes disponibles, las ordena por muestra y prepara la comparación. Las fotografías conservan su fuente y técnica.</p><p className="mt-4 text-xs text-sky-200">{collection.filter(e=>e.specimen==='blood').length} imágenes de sangre · {collection.length} preparaciones microscópicas y cultivos disponibles</p></header>
    <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Muestra<select className="mt-2 block w-full rounded-xl border border-slate-300 bg-white p-3" value={kind} onChange={e=>{setKind(e.target.value as SpecimenKind|'all');setSelectedId('');setCompareId('');}}><option value="all">Todas las preparaciones</option>{Object.entries(SPECIMEN_LABELS).map(([k,label])=><option key={k} value={k}>{label} ({collection.filter(e=>e.specimen===k).length})</option>)}</select></label><label className="text-sm font-semibold">Buscar microorganismo o técnica<input className="mt-2 block w-full rounded-xl border border-slate-300 bg-white p-3" value={query} onChange={e=>{setQuery(e.target.value);setCompareId('');}} placeholder="Plasmodium, Trypanosoma, Giemsa…"/></label></div>
    {!selected?<p className="rounded-xl border border-dashed p-6 text-sm">No hay preparaciones documentadas para este filtro. No se generan muestras ficticias para llenar la colección.</p>:<><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Preparación principal<select className="mt-2 block w-full rounded-xl border border-slate-300 bg-white p-3" value={selected.id} onChange={e=>setSelectedId(e.target.value)}>{filtered.map(e=><option key={e.id} value={e.id}>{e.image.caption}</option>)}</select></label><label className="text-sm font-semibold">Comparar con otra preparación<select className="mt-2 block w-full rounded-xl border border-slate-300 bg-white p-3" value={comparison?.id??''} onChange={e=>setCompareId(e.target.value)}><option value="">Sin comparación</option>{filtered.filter(e=>e.id!==selected.id).map(e=><option key={e.id} value={e.id}>{e.image.caption}</option>)}</select></label></div><div className={`grid items-start gap-5 ${comparison?'xl:grid-cols-2':''}`}><SlideViewer key={selected.id} entry={selected}/>{comparison&&<SlideViewer key={comparison.id} entry={comparison}/>}</div><p className="text-xs leading-6 text-slate-500">{selected.classificationNote} La procedencia de la imagen no demuestra circulación actual de ese agente en Guatemala.</p>{onSelectOrganism&&<button className="inline-flex items-center gap-2 text-sm font-semibold text-sky-800 underline" onClick={()=>onSelectOrganism(selected.organism)}><BookOpen size={16}/>Ver ficha de {selected.organism.scientificName}</button>}</>}
    <div className="rounded-xl border border-sky-100 bg-sky-50 p-4 text-sm leading-7"><h3 className="flex items-center gap-2 font-semibold text-sky-900"><Microscope size={18}/>Sangre: dos preparaciones complementarias</h3><p>En malaria, la gota gruesa concentra los parásitos; el frotis delgado ayuda a estudiar la morfología y la identificación de especie. La guía del CDC explica su examen microscópico. Estas imágenes de referencia permiten practicar observación, sin emitir resultados de un paciente.</p><a className="text-sky-800 underline" href="https://www.cdc.gov/dpdx/diagnosticprocedures/blood/microexam.html" target="_blank" rel="noopener noreferrer">CDC DPDx · examen microscópico de sangre</a></div><CdcAttribution/>
  </section>;
}
